version: "2.1"
services:
  wikijs:
    build:
      context: .
      dockerfile: Dockerfile.aarch64
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 30960:3000
    restart: unless-stopped
